AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.7
  Exclude:
  - 'lib/vernacular/ast/parser.rb'
  - 'test/typed_method_args_test.rb'
  - 'test/typed_method_returns_test.rb'
  - 'vendor/**/*'

Layout/LineLength:
  Max: 80
